package com.keanntech.framework.common.mapper;

import com.keanntech.framework.common.model.AdminRoleRelation;
import com.keanntech.framework.common.model.AdminRoleRelationExample;
import com.keanntech.framework.common.model.AdminRoleRelationKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdminRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    long countByExample(AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int deleteByExample(AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int deleteByPrimaryKey(AdminRoleRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int insert(AdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int insertSelective(AdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    List<AdminRoleRelation> selectByExample(AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    AdminRoleRelation selectByPrimaryKey(AdminRoleRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminRoleRelation record, @Param("example") AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByExample(@Param("record") AdminRoleRelation record, @Param("example") AdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByPrimaryKeySelective(AdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByPrimaryKey(AdminRoleRelation record);
}