package com.keanntech.framework.common.mapper;

import com.keanntech.framework.common.model.ResourceCategory;
import com.keanntech.framework.common.model.ResourceCategoryExample;
import com.keanntech.framework.common.model.ResourceCategoryKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ResourceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    long countByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int deleteByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int deleteByPrimaryKey(ResourceCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int insert(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int insertSelective(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    List<ResourceCategory> selectByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    ResourceCategory selectByPrimaryKey(ResourceCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") ResourceCategory record, @Param("example") ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByExample(@Param("record") ResourceCategory record, @Param("example") ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByPrimaryKeySelective(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    int updateByPrimaryKey(ResourceCategory record);
}