package com.keanntech.framework.common.mapper;

import com.keanntech.framework.common.model.SysAdminPermission;
import com.keanntech.framework.common.model.SysAdminPermissionExample;
import com.keanntech.framework.common.model.SysAdminPermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAdminPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    long countByExample(SysAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int deleteByExample(SysAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int deleteByPrimaryKey(SysAdminPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int insert(SysAdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int insertSelective(SysAdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    List<SysAdminPermission> selectByExample(SysAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    SysAdminPermission selectByPrimaryKey(SysAdminPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysAdminPermission record, @Param("example") SysAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int updateByExample(@Param("record") SysAdminPermission record, @Param("example") SysAdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int updateByPrimaryKeySelective(SysAdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    int updateByPrimaryKey(SysAdminPermission record);
}