package com.keanntech.framework.common.mapper;

import com.keanntech.framework.common.model.SysResourceCategory;
import com.keanntech.framework.common.model.SysResourceCategoryExample;
import com.keanntech.framework.common.model.SysResourceCategoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysResourceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    long countByExample(SysResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int deleteByExample(SysResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int deleteByPrimaryKey(SysResourceCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int insert(SysResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int insertSelective(SysResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    List<SysResourceCategory> selectByExample(SysResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    SysResourceCategory selectByPrimaryKey(SysResourceCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysResourceCategory record, @Param("example") SysResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByExample(@Param("record") SysResourceCategory record, @Param("example") SysResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByPrimaryKeySelective(SysResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    int updateByPrimaryKey(SysResourceCategory record);
}