package com.keanntech.framework.common.mapper;

import com.keanntech.framework.common.model.UmsResourceCategory;
import com.keanntech.framework.common.model.UmsResourceCategoryExample;
import com.keanntech.framework.common.model.UmsResourceCategoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsResourceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    long countByExample(UmsResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int deleteByExample(UmsResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int deleteByPrimaryKey(UmsResourceCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int insert(UmsResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int insertSelective(UmsResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    List<UmsResourceCategory> selectByExample(UmsResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    UmsResourceCategory selectByPrimaryKey(UmsResourceCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") UmsResourceCategory record, @Param("example") UmsResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int updateByExample(@Param("record") UmsResourceCategory record, @Param("example") UmsResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int updateByPrimaryKeySelective(UmsResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource_category
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    int updateByPrimaryKey(UmsResourceCategory record);
}