package com.keanntech.framework.common.model;

import java.io.Serializable;

public class AdminRoleRelation extends AdminRoleRelationKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_relation.admin_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_relation.role_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_relation.admin_id
     *
     * @return the value of admin_role_relation.admin_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_relation.admin_id
     *
     * @param adminId the value for admin_role_relation.admin_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role_relation.role_id
     *
     * @return the value of admin_role_relation.role_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role_relation.role_id
     *
     * @param roleId the value for admin_role_relation.role_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_relation
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminId=").append(adminId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}