package com.keanntech.framework.common.model;

import java.io.Serializable;
import java.util.Date;

public class Admin extends AdminKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.portrait
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.email
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.nick_name
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.description
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.update_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.update_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.enabled
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.deleted
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.locked
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private Boolean locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.portrait
     *
     * @return the value of admin.portrait
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.portrait
     *
     * @param portrait the value for admin.portrait
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.nick_name
     *
     * @return the value of admin.nick_name
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.nick_name
     *
     * @param nickName the value for admin.nick_name
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.description
     *
     * @return the value of admin.description
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.description
     *
     * @param description the value for admin.description
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_id
     *
     * @return the value of admin.create_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_id
     *
     * @param createId the value for admin.create_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.update_id
     *
     * @return the value of admin.update_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.update_id
     *
     * @param updateId the value for admin.update_id
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.update_time
     *
     * @return the value of admin.update_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.update_time
     *
     * @param updateTime the value for admin.update_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_time
     *
     * @return the value of admin.login_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_time
     *
     * @param loginTime the value for admin.login_time
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.enabled
     *
     * @return the value of admin.enabled
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.enabled
     *
     * @param enabled the value for admin.enabled
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.deleted
     *
     * @return the value of admin.deleted
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.deleted
     *
     * @param deleted the value for admin.deleted
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.locked
     *
     * @return the value of admin.locked
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.locked
     *
     * @param locked the value for admin.locked
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Tue Jun 23 09:06:40 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", portrait=").append(portrait);
        sb.append(", email=").append(email);
        sb.append(", nickName=").append(nickName);
        sb.append(", description=").append(description);
        sb.append(", createId=").append(createId);
        sb.append(", updateId=").append(updateId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", enabled=").append(enabled);
        sb.append(", deleted=").append(deleted);
        sb.append(", locked=").append(locked);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}