package com.keanntech.framework.common.model;

import java.io.Serializable;

public class SysAdminPermissionKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_permission.id
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_permission.id
     *
     * @return the value of sys_admin_permission.id
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_permission.id
     *
     * @param id the value for sys_admin_permission.id
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_permission
     *
     * @mbg.generated Fri Jun 26 21:54:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}