package com.keanntech.framework.common.model;

import java.io.Serializable;
import java.util.Date;

public class SysResourceCategory extends SysResourceCategoryKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.create_time
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.update_time
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.create_id
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.update_id
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.category_name
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.sort
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource_category.deleted
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.create_time
     *
     * @return the value of sys_resource_category.create_time
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.create_time
     *
     * @param createTime the value for sys_resource_category.create_time
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.update_time
     *
     * @return the value of sys_resource_category.update_time
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.update_time
     *
     * @param updateTime the value for sys_resource_category.update_time
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.create_id
     *
     * @return the value of sys_resource_category.create_id
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.create_id
     *
     * @param createId the value for sys_resource_category.create_id
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.update_id
     *
     * @return the value of sys_resource_category.update_id
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.update_id
     *
     * @param updateId the value for sys_resource_category.update_id
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.category_name
     *
     * @return the value of sys_resource_category.category_name
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.category_name
     *
     * @param categoryName the value for sys_resource_category.category_name
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.sort
     *
     * @return the value of sys_resource_category.sort
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.sort
     *
     * @param sort the value for sys_resource_category.sort
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource_category.deleted
     *
     * @return the value of sys_resource_category.deleted
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource_category.deleted
     *
     * @param deleted the value for sys_resource_category.deleted
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource_category
     *
     * @mbg.generated Wed Jun 24 08:38:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createId=").append(createId);
        sb.append(", updateId=").append(updateId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", sort=").append(sort);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}