package com.keanntech.framework.common.model;

import java.io.Serializable;
import java.util.Date;

public class UmsPermission extends UmsPermissionKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.pid
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.permission_name
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.value
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.icon
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.type
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.uri
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.description
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.sort
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.enable
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.create_id
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.update_id
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.create_time
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.update_time
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_permission.deleted
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_permission
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.pid
     *
     * @return the value of ums_permission.pid
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.pid
     *
     * @param pid the value for ums_permission.pid
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.permission_name
     *
     * @return the value of ums_permission.permission_name
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.permission_name
     *
     * @param permissionName the value for ums_permission.permission_name
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.value
     *
     * @return the value of ums_permission.value
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.value
     *
     * @param value the value for ums_permission.value
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.icon
     *
     * @return the value of ums_permission.icon
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.icon
     *
     * @param icon the value for ums_permission.icon
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.type
     *
     * @return the value of ums_permission.type
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.type
     *
     * @param type the value for ums_permission.type
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.uri
     *
     * @return the value of ums_permission.uri
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.uri
     *
     * @param uri the value for ums_permission.uri
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.description
     *
     * @return the value of ums_permission.description
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.description
     *
     * @param description the value for ums_permission.description
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.sort
     *
     * @return the value of ums_permission.sort
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.sort
     *
     * @param sort the value for ums_permission.sort
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.enable
     *
     * @return the value of ums_permission.enable
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.enable
     *
     * @param enable the value for ums_permission.enable
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.create_id
     *
     * @return the value of ums_permission.create_id
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.create_id
     *
     * @param createId the value for ums_permission.create_id
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.update_id
     *
     * @return the value of ums_permission.update_id
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.update_id
     *
     * @param updateId the value for ums_permission.update_id
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.create_time
     *
     * @return the value of ums_permission.create_time
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.create_time
     *
     * @param createTime the value for ums_permission.create_time
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.update_time
     *
     * @return the value of ums_permission.update_time
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.update_time
     *
     * @param updateTime the value for ums_permission.update_time
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_permission.deleted
     *
     * @return the value of ums_permission.deleted
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_permission.deleted
     *
     * @param deleted the value for ums_permission.deleted
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_permission
     *
     * @mbg.generated Sat Jun 20 22:19:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", permissionName=").append(permissionName);
        sb.append(", value=").append(value);
        sb.append(", icon=").append(icon);
        sb.append(", type=").append(type);
        sb.append(", uri=").append(uri);
        sb.append(", description=").append(description);
        sb.append(", sort=").append(sort);
        sb.append(", enable=").append(enable);
        sb.append(", createId=").append(createId);
        sb.append(", updateId=").append(updateId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}